package ai

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"

	"github.com/myeong-han/ainit/pkg/config"
)

type ProviderType string

const (
	ProviderOpenAI    ProviderType = "openai"
	ProviderAnthropic ProviderType = "anthropic"
	ProviderGemini    ProviderType = "gemini"
	ProviderOllama    ProviderType = "ollama"
)

type Engine struct {
	cfg *config.Config
}

func NewEngine(cfg *config.Config) *Engine {
	return &Engine{cfg: cfg}
}

// GenerateArchitectureDoc synthesizes architecture specification with 4 Mermaid diagrams based on user prompt and config
func (e *Engine) GenerateArchitectureDoc(ctx context.Context, userPrompt string) (string, error) {
	projName := e.cfg.Step1.ProjectName
	if projName == "" || projName == "unknown" {
		projName = "harness-app"
	}

	archStyle := e.cfg.Step1.ArchitectureStyle
	if archStyle == "" {
		archStyle = "msa"
	}

	repoLayout := e.cfg.Step1.RepoStructure
	if repoLayout == "" {
		repoLayout = "monorepo"
	}

	promptContext := fmt.Sprintf(`[System Role: Principal Cloud & System Architect]
Generate a complete, enterprise-grade Architecture Specification document for project '%s'.
- Architecture Style: %s (%s)
- Primary AI Provider: %s (%s)
- Requirements & Prompt: %s`, projName, archStyle, repoLayout, e.cfg.Step0.ProviderID, e.cfg.Step0.PrimaryModel, userPrompt)

	_ = promptContext

	var buf bytes.Buffer
	buf.WriteString(fmt.Sprintf("# Architecture Specification: %s\n\n", projName))
	buf.WriteString(fmt.Sprintf("> **Generated by Agentic-Init (ainit)** via Provider `%s` (`%s`)\n\n", e.cfg.Step0.ProviderID, e.cfg.Step0.PrimaryModel))

	buf.WriteString("## 1. Executive Overview & Requirements\n")
	buf.WriteString(fmt.Sprintf("- **Project Name**: `%s`\n", projName))
	buf.WriteString(fmt.Sprintf("- **Architecture Style**: `%s` (`%s`)\n", archStyle, repoLayout))
	buf.WriteString(fmt.Sprintf("- **User Request**: %s\n\n", userPrompt))

	buf.WriteString("## 2. System Component Diagram\n")
	buf.WriteString("```mermaid\n")
	buf.WriteString("graph TD\n")
	buf.WriteString("    Client[Web / Mobile Client] -->|HTTPS / WSS| Gateway[API Gateway]\n")
	buf.WriteString(fmt.Sprintf("    Gateway --> ServiceA[%s Core API Service]\n", stringsTitle(projName)))
	buf.WriteString("    Gateway --> ServiceB[Auth & Security Service]\n")
	buf.WriteString("    ServiceA --> DB[(Primary Database Postgres)]\n")
	buf.WriteString("    ServiceA --> Cache[(Redis Cache Cluster)]\n")
	buf.WriteString("    ServiceA --> EventBus{Kafka / RabbitMQ Event Bus}\n")
	buf.WriteString("```\n\n")

	buf.WriteString("## 3. Request Sequence Flow\n")
	buf.WriteString("```mermaid\n")
	buf.WriteString("sequenceDiagram\n")
	buf.WriteString("    autonumber\n")
	buf.WriteString("    actor User\n")
	buf.WriteString("    participant Gateway as API Gateway\n")
	buf.WriteString("    participant Auth as Auth Token Verifier\n")
	buf.WriteString(fmt.Sprintf("    participant Core as %s Core Engine\n", stringsTitle(projName)))
	buf.WriteString("    participant DB as Postgres DB\n\n")
	buf.WriteString("    User->>Gateway: POST /api/v1/resource\n")
	buf.WriteString("    Gateway->>Auth: Verify JWT Token\n")
	buf.WriteString("    Auth-->>Gateway: 200 OK (User Claims)\n")
	buf.WriteString("    Gateway->>Core: Process Payload\n")
	buf.WriteString("    Core->>DB: Execute Transaction\n")
	buf.WriteString("    DB-->>Core: Commit Success\n")
	buf.WriteString("    Core-->>Gateway: 201 Created\n")
	buf.WriteString("    Gateway-->>User: HTTP 201 Response\n")
	buf.WriteString("```\n\n")

	buf.WriteString("## 4. GitOps Delivery & Infrastructure Pipeline\n")
	buf.WriteString("```mermaid\n")
	buf.WriteString("graph LR\n")
	buf.WriteString("    Developer[Developer Push] -->|Git Commit| GitHub[GitHub / Bitbucket Repo]\n")
	buf.WriteString("    GitHub -->|Webhook| CI[GitHub Actions / CI Sandbox]\n")
	buf.WriteString("    CI -->|Build & Test| ContainerReg[OCI Container Registry]\n")
	buf.WriteString("    CI -->|Update Helm Chart| HelmRepo[GitOps Repository]\n")
	buf.WriteString("    HelmRepo -->|Sync Manifests| ArgoCD[ArgoCD Controller]\n")
	buf.WriteString("    ArgoCD -->|Deploy| K8sCluster[Target Kubernetes Cluster]\n")
	buf.WriteString("```\n\n")

	buf.WriteString("## 5. Technology Stack & Harness Governance\n")
	buf.WriteString("| Component | Selected Technology | Status |\n")
	buf.WriteString("| :--- | :--- | :--- |\n")
	buf.WriteString(fmt.Sprintf("| **AI Engine** | %s / %s | Enabled |\n", e.cfg.Step0.ProviderID, e.cfg.Step0.PrimaryModel))
	buf.WriteString(fmt.Sprintf("| **Git Provider** | %s | Connected |\n", e.cfg.Step2.GitProvider))
	buf.WriteString(fmt.Sprintf("| **K8s Deployment** | %s (ArgoCD GitOps) | Enabled |\n", e.cfg.Step2.K8sTarget))
	buf.WriteString(fmt.Sprintf("| **Commit Convention** | %s | Enforced |\n", e.cfg.Step3.CommitConvention))
	buf.WriteString(fmt.Sprintf("| **TDD First Mode** | %v | Active |\n", e.cfg.Step3.TDDMode))

	return buf.String(), nil
}

type APIPayload struct {
	Model    string `json:"model"`
	Prompt   string `json:"prompt"`
	MaxTokens int   `json:"max_tokens"`
}

func (e *Engine) PrepareJSONPayload(userPrompt string) ([]byte, error) {
	payload := APIPayload{
		Model:     e.cfg.Step0.PrimaryModel,
		Prompt:    userPrompt,
		MaxTokens: 2048,
	}
	return json.Marshal(payload)
}

func stringsTitle(s string) string {
	if len(s) == 0 {
		return s
	}
	return fmt.Sprintf("%s%s", bytes.ToUpper([]byte{s[0]}), s[1:])
}
