package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/myeong-han/ainit/pkg/config"
)

// GenerateAgentContextFiles generates agent context rules for all major AI agent platforms
func GenerateAgentContextFiles(targetDir string) error {
	files := map[string]string{
		"AGENTS.md": `# Agentic-Init (ainit) Execution Rules

## General Principles
1. **Atomic Micro-Commits**: All generated code must be committed in small, single-purpose commits.
2. **Commit Convention Compliance**: Every commit message MUST strictly adhere to the configured Commit Convention.
3. **PR Convention Compliance**: Every Pull Request MUST follow the generated PR template and satisfy all checklist criteria.
4. **TDD First**: Write failing test specifications prior to writing feature code.
5. **Local Sandbox Verification**: Execute build & test suites locally before executing git commit.
6. **Documentation Sync**: Keep Notion and Confluence documentation up-to-date via MCP integrations.
`,
		"CLAUDE.md": `# CLAUDE.md - Agent Context

> ⚠️ **CRITICAL AGENT INSTRUCTION**: This repository uses [AGENTS.md](./AGENTS.md) as the Single Source of Truth.
> Claude Code MUST strictly read, respect, and obey all instructions in AGENTS.md.
`,
		".cursorrules": `# Cursor Rules Configuration
- Always read AGENTS.md before making any code modifications.
- Execute unit tests (make test) before finalizing any changes.
`,
		filepath.Join(".github", "copilot-instructions.md"): `# GitHub Copilot Custom Instructions
All AI Copilot and Agent behaviors MUST be strictly governed by [AGENTS.md](../AGENTS.md).
`,
		".windsurfrules": `# Windsurf Rules Configuration
- Always read AGENTS.md before making any code modifications.
`,
		filepath.Join(".gemini", "rules"): `# Gemini & Antigravity Agent Rules
- Always read AGENTS.md before making any code modifications.
`,
	}

	for relPath, content := range files {
		fullPath := filepath.Join(targetDir, relPath)
		dir := filepath.Dir(fullPath)
		if err := os.MkdirAll(dir, 0755); err != nil {
			return err
		}
		if err := os.WriteFile(fullPath, []byte(content), 0644); err != nil {
			return err
		}
	}

	return nil
}

// GenerateGitOpsManifests generates K8s manifests, Helm charts & ArgoCD Application manifests
func GenerateGitOpsManifests(targetDir string, cfg *config.Config) error {
	projName := cfg.Step1.ProjectName
	if projName == "" {
		projName = "ainit-app"
	}

	gitopsDir := filepath.Join(targetDir, "gitops")
	helmDir := filepath.Join(gitopsDir, "helm", projName)
	argocdDir := filepath.Join(gitopsDir, "argocd")

	files := map[string]string{
		filepath.Join(helmDir, "Chart.yaml"): fmt.Sprintf(`apiVersion: v2
name: %s
description: Helm chart generated by Agentic-Init (ainit)
type: application
version: 0.1.0
appVersion: "1.0.0"
`, projName),

		filepath.Join(helmDir, "values.yaml"): fmt.Sprintf(`replicaCount: 2
image:
  repository: harbor.local/%s
  pullPolicy: IfNotPresent
  tag: "latest"
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: %s.local
      paths:
        - path: /
          pathType: Prefix
`, projName, projName),

		filepath.Join(argocdDir, "application.yaml"): fmt.Sprintf(`apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: %s-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/myeong-han/ainit.git
    targetRevision: HEAD
    path: gitops/helm/%s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
`, projName, projName),
	}

	for relPath, content := range files {
		dir := filepath.Dir(relPath)
		if err := os.MkdirAll(dir, 0755); err != nil {
			return err
		}
		if err := os.WriteFile(relPath, []byte(content), 0644); err != nil {
			return err
		}
	}

	return nil
}

// GenerateHarnessProject generates the complete architecture spec, Mermaid diagrams, and code structure
func GenerateHarnessProject(targetDir string, cfg *config.Config, plainTextPrompt string) error {
	if err := GenerateAgentContextFiles(targetDir); err != nil {
		return err
	}

	projName := cfg.Step1.ProjectName
	if projName == "" {
		projName = "ainit-app"
	}

	archDoc := fmt.Sprintf(`# %s Architecture Specification

## 1. Overview & Requirements
**AI Provider**: %s (%s)
**Primary Model**: %s
**Architecture Style**: %s
**Repository Structure**: %s

### Plain Text Architecture Prompt Requirements
> %s

---

## 2. Generated Mermaid Diagrams

### 2.1 Microservices & Middleware Overview
%s

### 2.2 Sequence Diagram
%s

### 2.3 Ingress Traffic Flow
%s

### 2.4 GitOps & CI/CD Pipeline Flow
%s

---

## 3. Harness Code Strategy
- **TDD Mode**: %v
- **Commit Convention**: %s
- **Local Sandbox Check**: %v
`,
		projName,
		cfg.Step0.ProviderID, cfg.Step0.LicensingMode,
		cfg.Step0.PrimaryModel,
		strings.ToUpper(cfg.Step1.ArchitectureStyle),
		cfg.Step1.RepoStructure,
		plainTextPrompt,
		renderMSAOverviewMermaid(cfg),
		renderSequenceMermaid(cfg),
		renderTrafficMermaid(cfg),
		renderGitOpsMermaid(cfg),
		cfg.Step3.TDDMode,
		cfg.Step3.CommitConvention,
		cfg.Step3.LocalSandboxTest,
	)

	docsDir := filepath.Join(targetDir, "docs")
	if err := os.MkdirAll(docsDir, 0755); err != nil {
		return err
	}

	specPath := filepath.Join(docsDir, "ARCHITECTURE_SPEC.md")
	return os.WriteFile(specPath, []byte(archDoc), 0644)
}

// GenerateAll sequentially executes /gen-docs, /gen-codes, and /gen-gitops
func GenerateAll(targetDir string, cfg *config.Config, prompt string) error {
	if err := GenerateHarnessProject(targetDir, cfg, prompt); err != nil {
		return fmt.Errorf("step 1 (/gen-docs & /gen-codes) failed: %v", err)
	}
	if err := GenerateGitOpsManifests(targetDir, cfg); err != nil {
		return fmt.Errorf("step 2 (/gen-gitops) failed: %v", err)
	}
	return nil
}

func renderMSAOverviewMermaid(cfg *config.Config) string {
	return "```mermaid\nflowchart LR\n    User([Client]) --> Gateway[API Gateway]\n    Gateway --> Auth[Auth Service]\n    Gateway --> Core[Core App Domain]\n    Core --> DB[(Database)]\n    Core --> Kafka[Event Broker]\n```"
}

func renderSequenceMermaid(cfg *config.Config) string {
	return "```mermaid\nsequenceDiagram\n    autonumber\n    Client->>Gateway: HTTP Request\n    Gateway->>Auth: Validate JWT Token\n    Auth-->>Gateway: 200 OK\n    Gateway->>Service: Process Business Logic\n    Service-->>Client: HTTP 200 Success\n```"
}

func renderTrafficMermaid(cfg *config.Config) string {
	return "```mermaid\nflowchart TD\n    Internet --> Ingress[Nginx Ingress / Emissary]\n    Ingress --> ServiceMesh[Istio Service Mesh]\n    ServiceMesh --> PodA[App Pod 1]\n    ServiceMesh --> PodB[App Pod 2]\n```"
}

func renderGitOpsMermaid(cfg *config.Config) string {
	return "```mermaid\nflowchart LR\n    GitPush([Git Commit Push]) --> Jenkins[Jenkins CI Test]\n    Jenkins --> Harbor[Container Registry Push]\n    Harbor --> ArgoCD[ArgoCD GitOps Sync]\n    ArgoCD --> K8s[Kubernetes Cluster]\n```"
}
